### ISSUE TITLE
DirectoryTree selected 的节点颜色没有改变

### ISSUE THREAD

**Issue by Error4767** [luffyZh/mini-dynamic-antd-theme#14]
树形控件，直接使用 Tree，selected 颜色正常改变，但具体的 DirectoryTree，selected 节点颜色还是 antd 的蓝色，不会改变颜色

**Comment by luffyZh** [comment]
@Error4767 
非常感谢，已经修复，有问题随时提～
![image](https://user-images.githubusercontent.com/17840558/142728445-337c68a3-cb78-4888-9531-5eb72ff1625e.png)
