### ISSUE TITLE
How change color theme without press button

### ISSUE THREAD

**Issue by yanielbf** [luffyZh/mini-dynamic-antd-theme#2]
How change color theme without press button? I need to do it when ComponentDidMount but only it works thus:
```
componentDidMount() {
    setTimeout(() => {
      changeAntdTheme(
        generateThemeColor('green')
      )
    }, 5000)
  }
```
I want to remove setTimeOut. Grettings

**Comment by luffyZh** [comment]
@yanielbf 
I haven't found any related bugs， i‘m use react hooks and the code as follow:

```
 useEffect(() => {
    changeAntdTheme(
      generateThemeColor('red')
    )
  }, []);
```
U can give me a repo url which has the problem and I try to fix it.
